server {
    listen 80;
    server_name localhost 192.168.1.52; # Thay bằng IP máy Ubuntu local của bạn hoặc domain local

    client_max_body_size 20M;

    # Chuyển các request chứa file tĩnh (CSS/JS/Images) cho Nginx xử lý trực tiếp
    location /static/ {
        alias /app/staticfiles/;
    }

    # Chuyển các file media (user upload)
    location /media/ {
        alias /app/media/;
    }

    # Chuyển toàn bộ request còn lại đến Gunicorn
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}